### ISSUE TITLE
Throws an exception when pubDate is not available on the feed

### ISSUE THREAD

**Issue by ramkumarkrk** [tylerrichey/feedparsercore#1]
When parsing it throws an exception when pubDate field is not available on the feed. The exception occurs on the method "GetElementValue" in the line "return (T)Convert.ChangeType(new object(), typeof(T));" 

Fixed it by making the following code change

if (fieldName == "pubDate")
	return (T)Convert.ChangeType(DateTime.Now, typeof(T)); 
else
	return (T)Convert.ChangeType(new object(), typeof(T));

**Comment by tylerrichey** [comment]
Fixed in 2.0.0!
